import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Router from "next/router";

import { useEffect } from "react";
import { useSelector } from "react-redux";
import { Card, CardContent, CardMedia, Container, Grid, Typography } from "@mui/material";

import styles from "../styles/Home.module.css";

export default function Base() {
  const state = useSelector((state) => state.album)

  useEffect(() => {
    if(state.album.length === 0){
      setTimeout(() => {
        Router.push("/")        
      }, 2000);
    }
  }, [state])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className={styles.title}> Images: </h1>
          <div >
            <button
              type="text"
              className={styles.button}
            >
              <Link href="/"> Add </Link>
            </button>
          </div>
          {state.album.length > 0 ?
        <div className={styles.grid}>
            <Container sx={{ py: 8 }} maxWidth="md">
              <Grid container spacing={4}>
                {state.album?.map((row,index) => (
                  <>
                  <Grid item key={index} xs={12} sm={6} md={4}>
                  <center><h4>---{row.tag}----</h4></center>
                    <Card >
                      <CardMedia
                        component="img"
                        height="200"
                        image={row.Image}
                        alt="green iguana"
                      />
                      <CardContent>
                        <Typography gutterBottom variant="h5" component="div">
                          Caption: {row.caption}
                        </Typography>
                       
                      </CardContent>
                    </Card>
                  </Grid>
                  </>
                ))}
              </Grid>
            </Container>
        </div>
            :
            <div style={{display:"block", margin: "10px 5px" }}>
              <p> Please add to album... </p>
            </div>
          }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
